main_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as core_views
from django.contrib.auth import views as auth_views

from . import views

from organizations.views import OrganizationCreate

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    path('listing_application_view/<int:listing_id>/', views.listing_application_view, name='listing_application_view'),
    # REST API
    path('listing_data/', views.ListingDataList.as_view(), name='listing_data'),
    path('listing_data/<int:pk>/', views.ListingDataDetail.as_view()),
    path('listing_user_group/', views.ListingUserGroupList.as_view(), name='listing_user_group'),
    path('listing_user_group/<int:pk>/', views.ListingUserGroupDetail.as_view()),
    path('general_table/', views.GeneralTableList.as_view(), name='general_table'),
    path('general_table/<int:pk>/', views.GeneralTableDetail.as_view()),
    path('date_table/', views.DateTableList.as_view(), name='date_table'),
    path('date_table/<int:pk>/', views.DateTableDetail.as_view()),
    path('time_table/', views.TimeTableList.as_view(), name='time_table'),
    path('time_table/<int:pk>/', views.TimeTableDetail.as_view()),
    path('price_table/', views.PriceTableList.as_view(), name='price_table'),
    path('price_table/<int:pk>/', views.PriceTableDetail.as_view()),
    # Others
    path('organization_create/', OrganizationCreate.as_view(), name='organization_create'),
    path('add_into_general_table/', views.add_into_general_table, name='add_into_general_table'),
    path('<int:general_data_id>/read_or_update_in_general_table/', views.read_or_update_in_general_table, name='read_or_update_in_general_table'),
    path('<int:general_data_id>/delete_in_general_table/', views.delete_in_general_table, name='delete_in_general_table'),
]

website_prototype_1/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import url
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from quickstart import views as quickstart_views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', quickstart_views.UserViewSet)
router.register(r'groups', quickstart_views.GroupViewSet)

from organizations.backends import invitation_backend

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('main_app/', include('main_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include(router.urls)),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('snippets/', include('snippets.urls')),
    url(r'^accounts/', include('organizations.urls')),
    url(r'^invitations/', include(invitation_backend().get_urls())),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
class ListingData(models.Model):
    item_of_interest = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    proposed_date = models.DateTimeField('proposed date')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    current_users = models.ManyToManyField(User, through='ListingUserGroup')
    def __str__(self):
        return self.item_of_interest

class ListingUserGroup(models.Model):
    listing_id = models.ForeignKey(ListingData, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)
    def __str__(self):
        return str(self.listing_id.item_of_interest) + ": " + str(self.user_id.username)

class GeneralTable(models.Model):
    listing_foreign_key = models.ForeignKey(ListingData, on_delete=models.CASCADE)
    general_data = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

class DateTable(models.Model):
    listing_foreign_key = models.ForeignKey(ListingData, on_delete=models.CASCADE)
    date_data = models.DateField()
    description = models.CharField(max_length=200)

class TimeTable(models.Model):
    listing_foreign_key = models.ForeignKey(ListingData, on_delete=models.CASCADE)
    time_data = models.TimeField()
    description = models.CharField(max_length=200)

class PriceTable(models.Model):
    listing_foreign_key = models.ForeignKey(ListingData, on_delete=models.CASCADE)
    price_data = models.FloatField(default=0)
    description = models.CharField(max_length=200)

main_app/forms.py
from django import forms
from .models import GeneralTable

class GeneralTableForm(forms.ModelForm):
    class Meta:
        model = GeneralTable
        fields = "__all__"

main_app/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.template import loader
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import ListingData

def index(request):
    request.session['top_navbar_location'] = 'home'
    return render(request, 'main_app/index.html', {})

@login_required
def dashboard(request):
    request.session['top_navbar_location'] = 'app1'
    listing_data_list = ListingData.objects.all()
    return render(request, 'main_app/dashboard.html', {'listing_data_list':listing_data_list})

def user_logout(request):
    logout(request)
    return redirect('main_app:index')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main_app:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'main_app/signup.html', {'form': form})

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('main_app:dashboard'))
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password: {}".format(username,password))
                return HttpResponse("Invalid login details given")
        else:
            form = AuthenticationForm()
        return render(request, 'main_app/login.html', {'form': form})
    else:
        return redirect('main_app:dashboard')

from django.contrib.auth.models import User
from .models import GeneralTable, DateTable, TimeTable, PriceTable

@login_required
def listing_application_view(request, listing_id):
    request.session['top_navbar_location'] = 'app1'
    try:
        listing_detail = ListingData.objects.get(pk=listing_id)
    except ListingData.DoesNotExist:
        raise Http404("Listing does not exist")
    request.session['current_listing_id'] = listing_id

    listing_general_data = GeneralTable.objects.filter(listing_foreign_key=listing_detail)
    listing_date_data = DateTable.objects.filter(listing_foreign_key=listing_detail)
    listing_time_data = TimeTable.objects.filter(listing_foreign_key=listing_detail)
    listing_price_data = PriceTable.objects.filter(listing_foreign_key=listing_detail)

    context = {'listing_detail': listing_detail,
    'listing_general_data': listing_general_data,
    'listing_date_data': listing_date_data,
    'listing_time_data': listing_time_data,
    'listing_price_data': listing_price_data,}
    return render(request, 'main_app/listing_application.html', context=context)

from .forms import GeneralTableForm
from .models import GeneralTable

@login_required
def add_into_general_table(request):
    if request.method == 'POST':
        form = GeneralTableForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_app:listing_application_view', kwargs={'listing_id': request.session['current_listing_id']}))
    else:
        form = GeneralTableForm()

    return render(request, 'main_app/add_into_general_table.html', {'form':form})

@login_required
def read_or_update_in_general_table(request, general_data_id):
    try:
        general_data = GeneralTable.objects.get(pk=general_data_id)
    except GeneralTable.DoesNotExist:
        return redirect('main_app:dashboard')
    form = GeneralTableForm(request.POST or None, instance = general_data)
    if form.is_valid():
       form.save()
       return redirect('main_app:listing_application_view', listing_id=request.session['current_listing_id'])
    return render(request, 'main_app/read_or_update_in_general_table.html', {'form':form, 'data': general_data})

@login_required
def delete_in_general_table(request, general_data_id):
    try:
        general_data = GeneralTable.objects.get(pk=general_data_id)
    except GeneralTable.DoesNotExist:
        return redirect('main_app:dashboard')
    general_data.delete()
    return redirect('main_app:listing_application_view', listing_id=request.session['current_listing_id'])

from .serializers import ListingDataSerializer, ListingUserGroupSerializer
from .serializers import GeneralTableSerializer, DateTableSerializer, TimeTableSerializer, PriceTableSerializer
from rest_framework import generics
from .models import ListingUserGroup
from .models import GeneralTable, DateTable, TimeTable, PriceTable


class ListingDataList(generics.ListCreateAPIView):
    queryset = ListingData.objects.all()
    serializer_class = ListingDataSerializer

class ListingDataDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = ListingData.objects.all()
    serializer_class = ListingDataSerializer

class ListingUserGroupList(generics.ListCreateAPIView):
    queryset = ListingUserGroup.objects.all()
    serializer_class = ListingUserGroupSerializer

class ListingUserGroupDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = ListingUserGroup.objects.all()
    serializer_class = ListingUserGroupSerializer

class GeneralTableList(generics.ListCreateAPIView):
    queryset = GeneralTable.objects.all()
    serializer_class = GeneralTableSerializer

class GeneralTableDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = GeneralTable.objects.all()
    serializer_class = GeneralTableSerializer

class DateTableList(generics.ListCreateAPIView):
    queryset = DateTable.objects.all()
    serializer_class = DateTableSerializer

class DateTableDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = DateTable.objects.all()
    serializer_class = DateTableSerializer

class TimeTableList(generics.ListCreateAPIView):
    queryset = TimeTable.objects.all()
    serializer_class = TimeTableSerializer

class TimeTableDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = TimeTable.objects.all()
    serializer_class = TimeTableSerializer

class PriceTableList(generics.ListCreateAPIView):
    queryset = PriceTable.objects.all()
    serializer_class = PriceTableSerializer

class PriceTableDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = PriceTable.objects.all()
    serializer_class = PriceTableSerializer

main_app/templates/main_app/add_into_general_table.html
{% extends 'main_app/base.html' %}

{% block content %}
<h1 class="cover-heading">Add General Data</h1>

<div style="text-align:left">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock %}

main_app/templates/main_app/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>Cover Template · Bootstrap</title>

  <!-- <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/cover/"> -->

  <!-- MDB icon -->
  {% load static %}
  <!-- <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Bootstrap core CSS -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="{% static 'logo_only.png' %}" sizes="128x127">
  <link rel="icon" href="{% static 'logo_only-32x32.png' %}" sizes="32x32" type="image/png">
  <link rel="icon" href="{% static 'logo_only-16x16.png' %}" sizes="16x16" type="image/png">
  <link rel="manifest" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg"
    color="#563d7c">
  <link rel="icon" href="{% static 'logo_only-16x16.ico' %}">
  <!-- <meta name="msapplication-config" content="https://getbootstrap.com/docs/4.4/assets/img/favicons/browserconfig.xml"> -->
  <!-- <meta name="theme-color" content="#563d7c"> -->

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <!-- <link href="https://getbootstrap.com/docs/4.4/examples/cover/cover.css" rel="stylesheet"> -->
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color darken-2">
      <div class="container">
        <!-- Navbar brand -->
        <a class="navbar-brand" href="{% url 'main_app:index' %}">
          <!-- <h3 class="masthead-brand">Cover</h3> -->
          <img src="{% static 'simple_logo_small.png' %}" class="card-img-top img-fluid" alt="My Logo">
        </a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            {# Django Home Link / Admin Link / Register Link#}
            {% if request.session.top_navbar_location == 'home' %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:index' %}">Home
              </a>
            </li>
            {% endif %}
            {% if request.session.top_navbar_location == 'app1' %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:dashboard' %}">Application 1
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:dashboard' %}">Application 1
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:signup' %}">Register</a>
            </li>

          </ul>
          <!-- Links -->

          <!-- Links -->
          <ul class="navbar-nav nav-flex-icons ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#!">
                <i class="fab fa-facebook-f" aria-hidden="true"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!">
                <i class="fab fa-twitter" aria-hidden="true"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!">
                <i class="fab fa-instagram" aria-hidden="true"></i>
              </a>
            </li>
          </ul>
          <!-- Links -->
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <!-- <a class="nav-item dropdown" href="{% url 'main_app:user_logout' %}">Logout</a> -->
          <div class="nav-item dropdown">
            <a class="nav-link btn dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-wrench"></i>
              <span class="d-none d-xl-inline-block ml-1">{{ user.username }}</span>
            </a>
            <div class="dropdown-menu dropdown-primary dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'main_app:user_logout' %}">Log Out</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
          {% else %}
          <a class="nav-link btn" href="{% url 'main_app:user_login' %}">Login</a>
          {% endif %}
          <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"><i class="fas fa-wrench"></i><span class="d-none d-xl-inline-block ml-1">Tools</span></a>
              <div class="dropdown-menu dropdown-primary dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li> -->

          <!-- <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form> -->
        </div>
        <!-- Collapsible content -->
      </div>
    </nav>
  </header>

  <main class="mt-5">
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </main>

  <footer class="page-footer font-small mdb-color darken-2 pt-4 mt-4">
    <div class="container">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a
          href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> MDBxxxxxxxx.com</a>
    </div>
  </footer>

  <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script> -->
  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>

</body>

</html>

main_app/templates/main_app/dashboard.html
{% extends 'main_app/base.html' %}
{% block content %}
<h1 class="cover-heading">Dashboard</h1>

<div style="text-align:left">
  {% if listing_data_list %}
  <ul>
    {% for listing_data in listing_data_list %}
    <li><a href="{% url 'main_app:listing_application_view' listing_data.id %}">{{ listing_data.item_of_interest }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No listing available.</p>
  {% endif %}
</div>
{% endblock %}

main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}
{% block content %}
<h1 class="cover-heading">Cover your page.</h1>
<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
<p class="lead">
  <a href="{% url 'main_app:dashboard' %}" class="btn btn-lg btn-secondary">Dashboard</a>
</p>
{% endblock %}

main_app/templates/main_app/listing_application.html
{% extends 'main_app/base.html' %}

{% block content %}
<h1 class="cover-heading">Listing Application</h1>

<div style="text-align:left">

<div class="row">
  <div class="col-sm">
    <p>{{ listing_detail.item_of_interest }}</p>
    <p>{{ listing_detail.price }}</p>
    <p>{{ listing_detail.proposed_date }}</p>
  
    <p>Author: {{ listing_detail.created_by.username }}</p>
  </div>

  <div class="col-sm">
    <p>List of users</p>
    {% if listing_detail.current_users.all %}
    <ol>
      {% for user in listing_detail.current_users.all %}
      <li>
        <div>
          <p>ID: <a href="#">{{ user.id }}</a></p>
          <p>Username: {{ user.username }}</p>
          <p>First name: {{ user.first_name }}</p>
          <p>E-mail: {{ user.email }}</p>
        </div>
      </li>
      {% endfor %}
    </ol>
    {% else %}
    <p>No user in here yet.</p>
    {% endif %}
  </div>

  <div class="col-sm">
    <p>General Data</p>
    <ul>
      {% for data in listing_general_data %}
      <li>
        <a href="{% url 'main_app:read_or_update_in_general_table' data.id %}">
          {{ data.description }}
        </a>
      </li>
      {% endfor %}
    </ul>
    <p class="lead">
      <a href="{% url 'main_app:add_into_general_table' %}" class="btn btn-sm btn-secondary">Add General Data</a>
    </p>
    <p>Date Data</p>
    <ul>
      {% for data in listing_date_data %}
      <li>
        {{ data.description }}
      </li>
      {% endfor %}
    </ul>
    <p>Time Data</p>
    <ul>
      {% for data in listing_time_data %}
      <li>
        {{ data.description }}
      </li>
      {% endfor %}
    </ul>
    <p>Price Data</p>
    <ul>
      {% for data in listing_price_data %}
      <li>
        {{ data.description }}
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

</div>

{% endblock %}

main_app/templates/main_app/login.html
{% extends 'main_app/base.html' %}
{% block content %}
<div class="container" style="color: black">
  <div class="jumbotron">
    <h1>Login here :</h1>
    <form method="post" action="{% url 'main_app:user_login' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/read_or_update_in_general_table.html
{% extends 'main_app/base.html' %}

{% block content %}
<h1 class="cover-heading">General Data</h1>

<div style="text-align:left">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    <a class="btn btn-danger" href="{% url 'main_app:delete_in_general_table' data.id %}">Delete</a>
</div>

{% endblock %}

main_app/templates/main_app/signup.html
{% extends 'main_app/base.html' %}

{% block content %}
<div class="container" style="color: black">
  <div class="jumbotron">
    <h2>Sign up</h2>
    <form method="post" style="text-align:left">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign up</button>
    </form>
  </div>
</div>
{% endblock %}